# Generated by Django 4.1.7 on 2023-02-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0004_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="WatchList",
            new_name="watchlist",
        ),
    ]
